builds:
  -
    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - darwin
      - linux
      - windows

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386 and amd64.
    goarch:
      - amd64
      - arm64

brews:
  -
    tap:
      owner: driessamyn
      name: homebrew-repo

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/driessamyn/deduplicater"

    # Your app's description.
    # Default is empty.
    description: "Find and manage duplicate files."